# Generated by Django 2.2 on 2019-04-27 18:47

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Login')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='repository/images', verbose_name='Imagem')),
                ('html_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='Url GitHub')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('html_url', models.CharField(max_length=300, verbose_name='Url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('fork', models.BooleanField(default=False, verbose_name='É Forkado?')),
                ('forks', models.IntegerField(default=0, verbose_name='Forks')),
                ('watchers', models.IntegerField(default=0, verbose_name='Watchers')),
                ('issues', models.IntegerField(default=0, verbose_name='Issues Reported')),
                ('contributors', models.IntegerField(default=0, verbose_name='Quantidade de Contribuidores')),
                ('stargazers_count', models.IntegerField(default=0, verbose_name='Estrelas')),
                ('has_wiki', models.BooleanField(default=False, verbose_name='Tem Wiki?')),
                ('languages', jsonfield.fields.JSONField()),
                ('score_languages', jsonfield.fields.JSONField(default={})),
                ('created_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='Criado em')),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='Útima atualização')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_owner', to='repository.Owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
