# Generated by Django 3.0.4 on 2020-04-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20200419_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/assets/img/language', verbose_name='Imagem'),
        ),
    ]
