# Generated by Django 2.0.6 on 2018-12-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_defaultuser_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultuser',
            name='extra_data',
        ),
    ]
