# Generated by Django 3.0.4 on 2020-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='key',
            field=models.CharField(default='python', max_length=100, verbose_name='Chave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
