# Generated by Django 3.0.4 on 2020-04-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='_type',
            new_name='job_type',
        ),
    ]
