# Generated by Django 2.2 on 2019-04-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_auth', '0001_initial'),
        ('job', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jc_candidate', to='users_auth.Candidate', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jc_job', to='job.Job', verbose_name='Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='company.Company', verbose_name='Company'),
        ),
    ]
